version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build --configuration Release
test_script:
  - ps: nunit3-console Mimick.Tests\bin\Release\net461\Mimick.Tests.dll --x86
  - ps: nunit3-console Mimick.Tests\bin\Release\netcoreapp2.0\Mimick.Tests.dll --x86
artifacts:
  - path: nugets\**\*.nupkg